import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../i18n";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // i18n
  const { i18n, t } = useTranslation();
  const [lang, setLang] = useState<string>(typeof window !== 'undefined' ? localStorage.getItem('lang') || 'es' : 'es');

  useEffect(() => {
    i18n.changeLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('lang', lang);
    }
  }, [lang, i18n]);

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div style={{ position: 'fixed', top: 10, right: 10, zIndex: 1000 }}>
          <select
            value={lang}
            onChange={e => setLang(e.target.value)}
            style={{ padding: '0.5rem', borderRadius: '0.5rem', border: '1px solid #ccc' }}
          >
            <option value="es">{t('spanish')}</option>
            <option value="en">{t('english')}</option>
          </select>
        </div>
        {children}
      </body>
    </html>
  );
}
